title = "GeekyGirlSarah"
baseURL = "https://geekygirlsarah.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://facebook.com/geekygirlsarah"
  twitter = "https://twitter.com/geekygirlsarah"
  instagram = "https://instagram.com/geekygirlsarah"
  youtube = ""
  github = "https://github.com/geekygirlsarah"
  gitlab = "https://gitlab.com/geekygirlsarah"
  linkedin = "https://linkedin.com/in/sarahwithee"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
